### PR TITLE
CATL-2102: Get Only Active Roles

### PR DESCRIPTION
**Pull request by lisandro-compucorp**
Overview
----------------------------------------
This PR solves a problem found in one of our forms, in which the current "Regional Case Worker" was not being shown, and it was displayed an old one instead.

Before
----------------------------------------
For a given role on a case, if it is changed, the relationship is marked as "inactive", with the appropriate `end_date` for it.
Later, when we access a webform that should display that relationship, only the first one is displayed, because it is not being filtered by `is_active`.

Here is an example of a field for a webform:
image

And also a list of values that the role "Regional Caseworker" could have:
image

After
----------------------------------------
The first active role found is displayed on the form.

### CODE REVIEW

**Comment by jamienovick** [comment]
@lisandro-compucorp @james-compucorp 

Ordering will work if there are multiple but if there is only 1 disabled relationship we should not load it.

I appreciate that the usage is unclear but we shouldn't load:

1. Relationships which are disabled
2. Relationships which have an end date in the past (<today)
3. Relationships which have a start date in the future (>today)

If something is opaque we should also consider whether adding a setting to let the user decide the behaviour will make it less opaque. For example a setting that would allow users to define whether inactive relationships should be loaded or not and help to explain the above.

@omarabuhussein @tunbola should this be a PR to webform core? I appreciate we have a deadline for NEU but still think this isn't a patch we want to carry? 

Thanks

**Comment by lisandro-compucorp** [comment]
@jamienovick Hey Jamie, thanks for your comments.

Let me tell you that filtering by `is_active` is the easiest approach for solving our current problem, but the method of this extension is clearly not working that way at this moment.

Some other parts of the code make usage of another param for checking active/inactive status of the result. Example https://github.com/compucorp/webform_civicrm/blob/7.x-5.1-patches/includes/wf_crm_webform_base.inc#L494

If we want to modify the current behaviour then it needs to be incorrect to return an inactive role. The change is very easy, it just needs to have sense.
And also, we are having a discussion on the original ticket (CATL-2102) for deciding to create or not a PR on the external repository. @tunbola can explain the situation better.

**Comment by tunbola** [comment]
@jamienovick , the best we can do with the API is to only fetch relationships where `is_active = 1` which signifies active relationships. To implement the condition you stated we would need something like `WHERE (start_date <= 'today' OR start_date is NULL ) AND end_date >= 'today' OR end_date IS NULL) which is not possible using the API and we shouldn't change the logic to use SQL queries since the API is better suited for communication between an extension and civi core. 

As regards putting this to webform_civicrm core, yes there is a plan to create a corresponding PR but our last PR was not approved because they requested for a corresponding D8 PR or that we pay them to port it, you can check the conversation here( https://github.com/colemanw/webform_civicrm/pull/458#issuecomment-770917794). So there is no guarantee that this would be approved also.

cc @lisandro-compucorp

**Comment by jamienovick** [comment]
@tunbola it feels like less work to do the D8 patch as well then to carry the customisation and manage it so I'd suggest we just accept that is part of what we need to do when it comes to webform, but we need to avoid patches in my opinion.

I think we should also change to use is_active = 1 at least then and ignore the start/end dates for now.

**Comment by tunbola** [comment]
Sure @jamienovick , The issue with porting to D8 is that, the files and code structures are totally different and because we don't have any client on webform_civicrm using D8 and no local setup for that, this makes it almost impossible to test if the same bugs exist on D8 and to QA or even determine if it needs a port or not. Not sure how we can proceed with that?
Maybe @hitesh-jain might have some ideas.

**Review by tunbola — APPROVED** [review]

**Pull request merged**
